version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_KEY=base64:DZFzqe8qNJW2Fl+y5vSKhwEL7u+hsnqw57FHCiwG1o8=
      - DB_CONNECTION=mysql
      - DB_HOST=containers-us-west-50.railway.app
      - DB_PORT=6373
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=GjCV4Em4IGEkuCfPdYo4
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=railway
      - MYSQL_USER=root
      - MYSQL_PASSWORD=GjCV4Em4IGEkuCfPdYo4
      - MYSQL_ROOT_PASSWORD=GjCV4Em4IGEkuCfPdYo4
